apiVersion: v1 
kind: PersistentVolumeClaim
metadata: 
  name: efs-claim
spec: 
  accessModes:
    - ReadWriteMany
  storageClassName: efs-sc
  resources:
    requests:
      storage: 5Gi #This storage is elastic,however; putting a value will prevent us from getting an error